- hosts: web
  tasks:
    - name: Installing httpd
      package:
        name: httpd
        state: present

    - name: Installing php
      package:
        name: php
        state: present

    - name: Copying web page
      template:
        src: web.php
        dest: /var/www/html

    - name: Starting httpd service
      service:
        name: httpd
        state: restarted

- hosts: lb
  tasks:
    - name: Installing haproxy
      package:
        name: haproxy
        state: present

    - name: Configuring haproxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: Starting haproxy
      service:
        name: haproxy
        state: restarted

    - name: Allow Firewall port https
      firewalld:
        port: 80/tcp
        state: enabled
        permanent: yes
        immediate: yes
